name: Version and release react-mm-jsr

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of release'
        required: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      - run: yarn add --dev mm-jsr
        working-directory: ./packages/react-mm-jsr
      - run: yarn test
        working-directory: ./packages/react-mm-jsr
  release:
    needs: unit-tests
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
      - run: yarn install --frozen-lockfile
      - run: yarn add --dev mm-jsr
        working-directory: ./packages/react-mm-jsr
      - run: yarn build
        working-directory: ./packages/react-mm-jsr
      - run: git config --global user.email "actions@github.com"
      - run: git config --global user.name "GH Actions"
      - run: yarn version --new-version ${{ github.event.inputs.version }}
        working-directory: ./packages/react-mm-jsr
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - run: npm publish
        working-directory: ./packages/react-mm-jsr
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true